apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: konsumo
# resources:
# - configmap.yaml
# - secret.yaml 

images:
- name: konsumo
  newName: dockerhub.io/scaps/konsumo
  newTag: "10"

patchesJson6902:
- path: route.yaml
  target:
    group: route.openshift.io
    kind: Route
    name: konsumo
    version: v1
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: konsumo
    version: v1
resources:
- ../../base
